FROM vocimage:latest

COPY ./vocabProvider-0.0.1-SNAPSHOT.jar /home/vocolProject/

WORKDIR /home/vocolProject/

COPY ./conf /home/vocolProject/conf

CMD java -jar vocabProvider-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENV PORT=8080

